### ISSUE TITLE
Missing VRTK4_UIPointer

### ISSUE THREAD

**Issue by clime57** [studentutu/VRTK4_Prefabs_Update_To_Tilia#1]
VRTK_References.cs

[SerializeField] private VRTK4_UIPointer leftHandUI_Pointer;
[SerializeField] private VRTK4_UIPointer rightHandUI_Pointer;

But I can't find VRTK4_UIPointer.

**Comment by studentutu** [comment]
You can try to load module https://github.com/studentutu/Tilia.UnityUI -> it has a full rig prefab and you can try to set it up
